# Generated by Django 5.1 on 2024-09-04 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fbought",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fbought", models.CharField(max_length=100)),
                ("fbamount", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("freeze", models.BooleanField(default=False)),
                ("expiry", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "fbought",
            },
        ),
        migrations.CreateModel(
            name="Fconsumed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fconsumed", models.CharField(max_length=100)),
                ("fcamount", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "fconsumed",
            },
        ),
        migrations.CreateModel(
            name="Ffreezer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ffreeze", models.CharField(max_length=100)),
                ("fnfreeze", models.CharField(max_length=100)),
                (
                    "fbought",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.fbought"
                    ),
                ),
            ],
            options={
                "db_table": "ffreezer",
            },
        ),
    ]
