# Generated by Django 5.1 on 2024-09-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ffreezer",
            name="fbought",
        ),
        migrations.AddField(
            model_name="ffreezer",
            name="ffbought",
            field=models.CharField(default="apple", max_length=100),
            preserve_default=False,
        ),
    ]
