# Generated by Django 5.1 on 2024-09-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fconsumed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fconsumed", models.CharField(max_length=100)),
                ("famount", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
            ],
            options={
                "db_table": "fconsumed",
            },
        ),
        migrations.RemoveField(
            model_name="fbought",
            name="fid",
        ),
    ]
