# Generated by Django 5.1 on 2024-09-02 12:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_fconsumed_remove_fbought_fid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fbought",
            old_name="famount",
            new_name="fbamount",
        ),
        migrations.RenameField(
            model_name="fconsumed",
            old_name="famount",
            new_name="fcamount",
        ),
    ]
