# Generated by Django 5.1 on 2024-09-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_remove_ffreezer_fbought_ffreezer_ffbought"),
    ]

    operations = [
        migrations.AddField(
            model_name="fconsumed",
            name="food_freeze",
            field=models.BooleanField(default=False),
        ),
    ]
