# Generated by Django 5.1 on 2024-09-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_fconsumed_food_freeze"),
    ]

    operations = [
        migrations.AddField(
            model_name="fbought",
            name="fcategory",
            field=models.CharField(default="vegetable", max_length=100),
            preserve_default=False,
        ),
    ]
