# Generated by Django 5.1 on 2024-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_fbought_fcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_name", models.CharField(max_length=100)),
                ("food_calorie", models.CharField(max_length=100)),
                ("food_category", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "food",
            },
        ),
    ]
