# Generated by Django 5.1 on 2024-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_food"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="fprice",
            field=models.CharField(default=200, max_length=100),
            preserve_default=False,
        ),
    ]
