# Generated by Django 5.1 on 2024-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_food_fprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="food_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
