# Generated by Django 5.1 on 2024-09-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_food_food_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="food",
            name="food_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="food",
            unique_together={("food_name", "food_category")},
        ),
    ]
