# Generated by Django 5.1 on 2024-09-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_alter_food_food_name_alter_food_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="food",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="food",
            name="food_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
